title: Binbin Tu's Homepage
page-top-title: Binbin Tu
top-section-bg-text: Be what you wanna be
home-subtitle: Binbin Tu&ensp;|&ensp; 涂彬彬
copyright-text: '&copy; Binbin Tu 2025-2030. All Rights Reserved.'
